name: iteh-app

services:

  database:
    image: postgres:16-alpine
    env_file:
      - ./env/database.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    image: iteh-backend
    env_file:
      - ./env/backend.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: iteh-frontend
    env_file:
      - ./env/frontend.env
    ports:
      - "7000:7000"

volumes:
  postgres-data:
